# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-21 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='year',
        ),
    ]
