# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=512)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=64)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('medium', 'Medium'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='trivial', max_length=8)),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='bug', max_length=7)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.CharField(default=' ', editable=False, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.Ticket'),
        ),
    ]
