# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-17 15:57
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='image',
            new_name='screenshot',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('critical', 'Critical'), ('major', 'Major'), ('medium', 'Medium'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='null', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='null', max_length=11),
            preserve_default=False,
        ),
    ]
