# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180918_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('medium', 'Medium'), ('minor', 'Minor'), ('trivial', 'Trivial')], default='trivial', max_length=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='bug', max_length=7),
        ),
    ]
