# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180919_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.CharField(default=' ', max_length=254),
        ),
    ]
