# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20180920_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, default='images/none/no-img.jpg', upload_to='images'),
        ),
    ]
